project:
  type: website
  output-dir: _site

website:
  title: "Corcovilos Lab"
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - publications.qmd
      - teaching.qmd
      - blog.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/TedCorcovilos
      - icon: github
        href: https://github.com/corcoted
      - icon: linkedin
        href: https://www.linkedin.com/in/ted-corcovilos
  page-footer: "Copyright 2023, Ted Corcovilos"
  google-analytics: UA-114117860-1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    author:
      - name: Theodore A. Corcovilos
        id: tac
        email: corcovilost@duq.edu
        affiliation:
          - name: Duquesne University
            city: Pittsburgh
            state: PA
            url: www.duq.edu



