project:
  type: website
  output-dir: _site

website:
  title: "Ted Corcovilos's personal page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd
      - blog.qmd
  page-footer: "Copyright 2023, Ted Corcovilos"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



