---
layout: post
title: Our New Master's Program
categories:
  - teaching
  - masters
  - planning
date: 2022-03-15
abstract: >-
  I discuss how we built our new Professional Master's in Applied Physics program at Duquesne.
---

*The opinions here are my personal point of view and not endorsed by Duquesne University or the Duquesne Physics Department.*

We just finished a recruiting blitz for our new Professional Master's Degree in Applied Physics program.[^1]
I thought it would be useful to share some insights I've had about the program creation process and our design philosophy.

Here is a recording of my formal presentation (an earlier version), but below I discuss how all of this came to be.

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/q42RyIOcnsc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>

## Initial steps
The idea of having a professional master's program was first formally stated in 2014 during a periodic external departmental review as a way for the department to grow while complementing the strong research output of our faculty.
The "professional" part came out of
1. the need to differentiate our proposed program from the traditional (academic) master's programs already in place at the larger research universities in Pittsburgh,
2. a growing pressure for "workforce development" and putting students directly into jobs, and
3. the unfair perception of a physics master's degree being primarily for those students who drop out of Ph.D. programs.

(Also, we wanted to avoid the phrase "terminal master's," which sounds too much like some horrible illness.)

The basic idea of professional programs is to add business skills to the curriculum.
At the time, we left things at that, as only a vague picture of where we were going, but it was enough to
start going through the administrative processes for starting a new program.

## Fact finding
Pretty quickly we realized that our new program couldn't just mix a sprinkle of business courses with graduate versions of undergrad classes (Graduate E&M, Graduate Quantum, etc.).
But those physics courses were all classes that we understood, because all of the faculty took classes like that in our Ph.D. work.
What to replace those with was not so obvious.
We did, however, have a clear goal for our students: _to get them jobs._

So, we went out and started talking to people who had jobs.

By that, I mean that we started talking to recent alumni who were working in industry, either immediately after graduating with a bachelor's degree or who had gone on to a graduate degree before entering the non-academic workforce.
Our department chair contacted a couple of former students that she had kept in touch with, and we arranged to visit them.
I also reached out to [my former students](/group.qmd#former-members) who were just starting in their jobs.

We asked a set of simple questions:
* What do you do?
* What did you learn as an undergraduate that prepared you for your job?
* What skills did you have to learn after you started your job?
* How does your education as a physicist distinguish you from coworkers?

The answers we got were perhaps not surprising, but they showed us our blind spots coming from the academic world.
Some of the key items were
* Hands-on experience with _specific_ equipment and software.  (Shout out to Sean Krupa for providing a detailed list.)
* Knowledge of how industrial R&D works.  From mundane things like terminology (e.g. I had no idea what [Tech Readiness Levels](https://en.wikipedia.org/wiki/Technology_readiness_level) were) to broader concepts like stakeholder interest, care and feeding of intellectual property, project life-cycles, allocation of effort, and organizational patterns.
* Communication, communication, communication.  Everything from how to present at weekly meetings, proper business email etiquette, writing formal progress reports, to requesting funds from higher-ups or investors. One general theme was presenting technical information to non-technical audiences.

We also talked with the co-workers and bosses of some of our alumni.
It was also encouraging to hear how useful a physics education is in the workplace beyond the obvious things.
Some highlights:
* Resilience - physicists are tenacious problem solvers who don't give up easily when solutions are not apparent or require many steps, and they are not discouraged by failure.
* Flexibility - physicists are great at working outside their comfort zone and learning new things when needed.

With notes in hand, we set out to combine those best attributes of a traditional academic physics education with the skills we saw used in real jobs.
This lead to four program learning objectives.  Upon completion of the program, our students will
1. Demonstrate _content knowledge_ relevant to current science and technology enterprises,
2. Demonstrate knowledge and skills for _measurement and control_ of physical variables,
3. Develop and use _computational models and simulations_ of physical phenomena and processes, and acquire, process, and analyze data from experiments, and
4. _Communicate_ scientific, technical, and professional information in variety of formats used in industrial/business settings: written and oral, formal and informal.

## Synthesis
The final key component was also the first: our faculty.
To make this program fly we had to lean into our strengths, so we created courses that match the expertise already in place.

### Technical Core
Rather than more traditional physics course offerings, we selected specific skills that our faculty have that translate to a commercial or government R&D environment.
The courses are lecture-lab hybrids, to give our students hands-on experience with equipment and techniques.

For my part, I'll be teaching "Advanced Optical Theory and Devices."
I took Sean's notes and identified a handful of projects that tie together concepts and techniques used in optical systems.
Tentatively, the main themes are imaging, interferometry, and optical sensing.
Students will design and build full optical systems using industrial software and tools.

Let me briefly highlight a few other courses.
* [Fatiha Benmokhtar](https://www.duq.edu/academics/faculty/fatiha-benmokhtar) will teach "Data Acquisition and Control" using her experience with high speed electronics from working on particle accelerator experiments.
* [Monica Sorescu](https://www.duq.edu/academics/faculty/monica-sorescu) will teach "Materials Science", showcasing her expertise in the synthesis and characterization of nanomaterials.
* We are very fortunate to be joined by Yang Wang, Senior Computational Scientist at the [Pittsburgh Supercomputing Center](https://www.psc.edu/).  He will bring his skills in high performance computing for the modeling of quantum materials to our "Computational Physics" course.

### Business Core
The other key element of our program is a set of foundational business courses to prepare our students for the corporate world as either potential managers or entrepreneurs.
Our colleagues at the [Palumbo-Donahue School of Business](https://www.duq.edu/academics/schools/business) worked with us to find a set of courses that wil give our graduates a head start.
We also are aiming for maximum flexibility, so we picked classes that are available as either traditional or on-line courses.

While this topic is out of my wheelhouse, I think our students will be well-prepared to think about product life-cycles and business development from root to stem.
### Real-world experience
Lastly, our program includes an industrial internship and capstone project.
Developing this has been a fun one for me.  I stepped outside my comfort zone to meet with tech industry leaders here in Pittsburgh, seeking partners willing to host students.
Pittsburgh is a regional hub for a lot of the big names in data and tech, and robotics has a strong presence locally.
I'm not allowed to name-drop yet, but I've been talking to companies working on things as varied as self-driving vehicles, materials science, quantum computing, and AI.

## Putting out our shingle
If you've read this far, you can probably see how excited I am about what we've built.
But we're still missing the most important component: students!
Building up the recruiting campaign for this new program has been another novel experience for me.
Let's just say we're trying it all: web ads, direct email, direct mail, Facebook, Linked-In, job fairs, and probably a half-dozen other avenues.
I've never been involved with this side of the university before.  Our undergraduate admissions is largely automatic from the perspective of the faculty.
Graduate recruiting, however, needs a more personal touch.  We had to get the message just right to connect with folks that best match our program.
We lack the name recognition of larger schools, but I hope our attention to detail and the care that went into building this program comes through to our prospectives.
Time will tell, but we're getting a good response so far.

[^1]: (Follow up note.) Ultimately, the program did not get the green light.  After two years of recruiting (albeit during and following the COVID pandemic) we weren't able to meet our minimum quota to proceed.  The experience was valuable, though.  Some of what we learned helped during the formation of the new [School of Science and Engineering](http://www.duq.edu/academics/colleges-and-schools/science-and-engineering/index.php) in 2023.